name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # или main, если у тебя основная ветка называется main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          npm install -g @angular/cli
          ng build --configuration production --base-href /ServiceDeskIntegration/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/ServiceDeskBotIntegration/browser  # или ./dist/имя-проекта
